/* BloxVerse service worker — generated by scripts/build-sw.mjs. Do not edit. */
const BUILD_ID = '2438c2495e1f';
const CACHE = 'bloxverse-' + BUILD_ID;
const PRECACHE = [
  '404.html',
  'admin.html',
  'auth.html',
  'avatar.html',
  'ban.html',
  'community-guidelines.html',
  'docs.html',
  'download.html',
  'favicon.svg',
  'friends.html',
  'game-detail.html',
  'game.html',
  'icons.svg',
  'importmap.json',
  'index.html',
  'js/parts.js',
  'js/sw-register.js',
  'marketplace.html',
  'privacy.html',
  'profile.html',
  'search.html',
  'settings.html',
  'src/accessories.js',
  'src/animate.js',
  'src/api.js',
  'src/app-detect.js',
  'src/auth.css',
  'src/auth.js',
  'src/avatar-clothing.js',
  'src/bloxverse-engine.js',
  'src/clothing.js',
  'src/counter.js',
  'src/emotes.js',
  'src/faces.js',
  'src/firebase.js',
  'src/friends.js',
  'src/game-scripts.js',
  'src/games.js',
  'src/instances.js',
  'src/leaderboard.js',
  'src/main.css',
  'src/multiplayer.js',
  'src/paths.js',
  'src/rpc.js',
  'src/scriptRuntime.js',
  'src/search.css',
  'src/servers.js',
  'src/style.css',
  'src/theme.css',
  'src/theme.js',
  'support.html',
  'terms.html',
  'transactions.html',
];

// Heavy CDN module files (three.js, firebase, cannon-es, glin-profanity).
// CORS-enabled and version-pinned, so we precache them too — every page then
// loads these from the service worker cache instead of the network.
const CDN_PRECACHE = [
  'https://esm.sh/three@0.184.0',
  'https://esm.sh/cannon-es@0.20.0',
  'https://esm.sh/glin-profanity@3.3.0',
  'https://www.gstatic.com/firebasejs/12.12.1/firebase-app.js',
  'https://www.gstatic.com/firebasejs/12.12.1/firebase-auth.js',
  'https://www.gstatic.com/firebasejs/12.12.1/firebase-firestore.js',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      // allSettled: one flaky URL must never abort the whole install — cache
      // whatever succeeds and activate anyway.
      .then((cache) => Promise.allSettled(
        PRECACHE.concat(CDN_PRECACHE).map((p) => cache.add(new Request(new URL(p, self.location))))
      ))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
      // After a deploy the old service worker can leave tabs on a stale mix
      // of files (new HTML importing exports the cached JS doesn't have yet),
      // which surfaces as 'module does not provide an export'. Reload any
      // controlled tabs once so everyone lands on the fresh, consistent build.
      .then(() => Promise.all(
        self.clients.matchAll({ type: 'window' }).then((clients) =>
          clients.map((client) => client.navigate(client.url).catch(() => {}))
        )
      ))
  );
});

// Small, changeable files are re-fetched in the background after a cache hit
// so updates propagate. Large media/models are cache-only (no background
// re-download) and refresh on the next deploy via the new BUILD_ID cache.
function isRevalidatable(pathname) {
  return !pathname.startsWith('/assets/') && !pathname.startsWith('/scratch/');
}

// CDN hosts whose module files (three.js, firebase, cannon-es, glin-profanity)
// are heavy and CORS-enabled. Without caching these, the browser re-downloads
// hundreds of KB from the CDN on every single load, which is what makes the
// site feel slow even when the service worker is installed.
const CDN_HOSTS = new Set(['esm.sh', 'www.gstatic.com']);

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  if (url.origin !== self.location.origin) {
    if (!CDN_HOSTS.has(url.hostname)) return;
    event.respondWith(caches.open(CACHE).then((cache) =>
      cache.match(url.href).then((cached) => {
        const network = fetch(request).then((res) => {
          if (res && res.ok && (res.type === 'basic' || res.type === 'cors')) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(url.href, copy));
          }
          return res;
        }).catch(() => cached);
        return cached || network;
      })
    ));
    return;
  }

  if (url.pathname === self.location.pathname) return;

  const promise = caches.open(CACHE).then((cache) => {
    let key = url;
    if (request.mode === 'navigate') {
      let p = url.pathname;
      if (p.endsWith('/')) p += 'index.html';
      // The site links to pages without extensions (/bloxverse/marketplace),
      // so map those to the precached .html file, otherwise every such
      // navigation misses the cache and re-fetches from the network.
      else if (!/\.[a-z0-9]+$/i.test(p)) p += '.html';
      key = new URL(p, self.location);
    }

    const options = request.mode === 'navigate' ? { ignoreSearch: true } : {};
    return cache.match(key.href, options).then((cached) => {
      if (cached && !isRevalidatable(url.pathname)) return cached;

      const network = fetch(request).then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(key.href, copy));
        }
        return res;
      }).catch(() => cached);

      return cached || network;
    });
  });

  event.respondWith(promise);
});
