/* BloxVerse service worker -- generated by scripts/build-sw.mjs. Do not edit. */
const BUILD_ID = '664c99aa1934';
const CACHE = 'bloxverse-' + BUILD_ID;
const PRECACHE = [
  '404.html',
  'account.html',
  'admin.html',
  'auth.html',
  'avatar.html',
  'ban.html',
  'catalog.html',
  'community-guidelines.html',
  'docs.html',
  'download.html',
  'favicon.svg',
  'friends.html',
  'game-detail.html',
  'game.html',
  'groups.html',
  'icons.svg',
  'importmap.json',
  'index.html',
  'inventory.html',
  'js/parts.js',
  'js/sw-register.js',
  'login.html',
  'privacy.html',
  'profile.html',
  'search.html',
  'settings.html',
  'src/accessories.js',
  'src/account_page.css',
  'src/account_page.js',
  'src/action-dialog.js',
  'src/animate.js',
  'src/api.js',
  'src/app-detect.js',
  'src/auth.css',
  'src/auth.js',
  'src/avatar-clothing.js',
  'src/avatar-viewer.js',
  'src/avatar_page.css',
  'src/avatar_page.js',
  'src/bloxverse-engine.js',
  'src/catalog-thumbnails.js',
  'src/catalog.css',
  'src/catalogStore.js',
  'src/catalog_model.js',
  'src/catalog_page.js',
  'src/catalog_stock.js',
  'src/catalog_view.js',
  'src/clothing.js',
  'src/counter.js',
  'src/download.css',
  'src/emotes.js',
  'src/faces.js',
  'src/firebase.js',
  'src/friends.js',
  'src/game-scripts.js',
  'src/game_page.css',
  'src/game_page.js',
  'src/games.js',
  'src/groups_page.css',
  'src/groups_page.js',
  'src/home.css',
  'src/home_model.js',
  'src/instances.js',
  'src/inventory_page.css',
  'src/inventory_page.js',
  'src/item-preview.js',
  'src/leaderboard.js',
  'src/legacyscriptRuntime.js',
  'src/main.css',
  'src/motion.js',
  'src/multiplayer.js',
  'src/navigation-indicator.js',
  'src/paths.js',
  'src/profile.css',
  'src/scriptRuntime.js',
  'src/search.css',
  'src/servers.js',
  'src/shell.js',
  'src/social_page.css',
  'src/social_page.js',
  'src/studio.js',
  'src/style.css',
  'src/theme.css',
  'src/theme.js',
  'src/tooltips.js',
  'src/transactions.css',
  'src/transactions.js',
  'support.html',
  'terms.html',
  'transactions.html',
];

// Heavy CDN module files (three.js, firebase, cannon-es, glin-profanity).
// CORS-enabled and version-pinned, so we precache them too -- every page then
// loads these from the service worker cache instead of the network.
const CDN_PRECACHE = [
  'https://esm.sh/three@0.184.0',
  'https://esm.sh/cannon-es@0.20.0',
  'https://esm.sh/glin-profanity@3.3.0',
  'https://www.gstatic.com/firebasejs/12.12.1/firebase-app.js',
  'https://www.gstatic.com/firebasejs/12.12.1/firebase-auth.js',
  'https://www.gstatic.com/firebasejs/12.12.1/firebase-firestore.js',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      // allSettled: one flaky URL must never abort the whole install -- cache
      // whatever succeeds and activate anyway.
      .then((cache) => Promise.allSettled(
        PRECACHE.concat(CDN_PRECACHE).map((p) => cache.add(new Request(new URL(p, self.location))))
      ))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
      // After a deploy the old service worker can leave tabs on a stale mix
      // of files (new HTML importing exports the cached JS doesn't have yet),
      // which surfaces as 'module does not provide an export'. Reload any
      // controlled tabs once so everyone lands on the fresh, consistent build.
      .then(() => Promise.all(
        self.clients.matchAll({ type: 'window' }).then((clients) =>
          clients.map((client) => client.navigate(client.url).catch(() => {}))
        )
      ))
  );
});

// Heavy media/models are cache-only and refresh on the next deploy via the new
// BUILD_ID cache. Everything else (HTML/CSS/JS) is network-first, so a deploy is
// visible on the very next load instead of one load later.
function isCacheOnly(pathname) {
  return pathname.startsWith('/assets/') || pathname.startsWith('/scratch/');
}

// CDN hosts whose module files (three.js, firebase, cannon-es, glin-profanity)
// and stylesheet/icon fonts (Font Awesome) are heavy and CORS-enabled. Without
// caching these, the browser re-downloads hundreds of KB from the CDN on every
// single load, which is what makes the site feel slow even when the service
// worker is installed. cdnjs matters most: it serves the two Font Awesome
// woff2 files, ~253KB combined, and they were previously missing here.
const CDN_HOSTS = new Set(['esm.sh', 'www.gstatic.com', 'cdnjs.cloudflare.com']);

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  if (url.origin !== self.location.origin) {
    if (!CDN_HOSTS.has(url.hostname)) return;
    event.respondWith(caches.open(CACHE).then((cache) =>
      cache.match(url.href).then((cached) => {
        const network = fetch(request).then((res) => {
          if (res && res.ok && (res.type === 'basic' || res.type === 'cors')) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(url.href, copy));
          }
          return res;
        }).catch(() => cached);
        return cached || network;
      })
    ));
    return;
  }

  if (url.pathname === self.location.pathname) return;

  const promise = caches.open(CACHE).then((cache) => {
    let key = url;
    if (request.mode === 'navigate') {
      let p = url.pathname;
      if (p.endsWith('/')) p += 'index.html';
      // The site links to pages without extensions (/bloxverse/catalog),
      // so map those to the precached .html file, otherwise every such
      // navigation misses the cache and re-fetches from the network.
      else if (!/\.[a-z0-9]+$/i.test(p)) p += '.html';
      key = new URL(p, self.location);
    }

    const options = request.mode === 'navigate' ? { ignoreSearch: true } : {};
    return cache.match(key.href, options).then((cached) => {
      if (cached && isCacheOnly(url.pathname)) return cached;

      // Network-first: serve the fresh response and refresh the cache behind it.
      // The old stale-while-revalidate order returned `cached` and revalidated in
      // the background, so every deploy cost one extra load before any page
      // showed the new markup, JS or CSS. Falling back to the cache only when
      // the network fails still keeps the app usable offline.
      const network = fetch(request).then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(key.href, copy));
        }
        return res;
      }).catch(() => cached);

      // If there is no cached copy to fall back on, respondWith would be handed
      // undefined and throw. Return a real Response instead.
      return network.then((res) => res || new Response('Offline', {
        status: 503,
        headers: { 'Content-Type': 'text/plain' },
      }));
    });
  });

  event.respondWith(promise);
});
