/* BloxVerse service worker — generated by scripts/build-sw.mjs. Do not edit. */
const BUILD_ID = '1ab725c618dd';
const CACHE = 'bloxverse-' + BUILD_ID;
const PRECACHE = [
  '404.html',
  'admin.html',
  'auth.html',
  'avatar.html',
  'ban.html',
  'community-guidelines.html',
  'docs.html',
  'favicon.svg',
  'friends.html',
  'game-detail.html',
  'game.html',
  'icons.svg',
  'importmap.json',
  'index.html',
  'js/crossbridges.js',
  'js/parts.js',
  'js/sw-register.js',
  'marketplace.html',
  'privacy.html',
  'profile.html',
  'search.html',
  'settings.html',
  'src/accessories.js',
  'src/auth.css',
  'src/auth.js',
  'src/avatar-clothing.js',
  'src/bloxverse-engine.js',
  'src/clothing.js',
  'src/counter.js',
  'src/emotes.js',
  'src/faces.js',
  'src/firebase.js',
  'src/friends.js',
  'src/game-scripts.js',
  'src/games.js',
  'src/instances.js',
  'src/leaderboard.js',
  'src/main.css',
  'src/multiplayer.js',
  'src/paths.js',
  'src/scriptRuntime.js',
  'src/search.css',
  'src/servers.js',
  'src/style.css',
  'src/theme.css',
  'src/theme.js',
  'studio.html',
  'support.html',
  'terms.html',
  'transactions.html',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE.map((p) => new Request(new URL(p, self.location)))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Small, changeable files are re-fetched in the background after a cache hit
// so updates propagate. Large media/models are cache-only (no background
// re-download) and refresh on the next deploy via the new BUILD_ID cache.
function isRevalidatable(pathname) {
  return !pathname.startsWith('/assets/') && !pathname.startsWith('/scratch/');
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname === self.location.pathname) return;

  const promise = caches.open(CACHE).then((cache) => {
    let key = url;
    if (request.mode === 'navigate') {
      let p = url.pathname;
      if (p.endsWith('/')) p += 'index.html';
      key = new URL(p, self.location);
    }

    const options = request.mode === 'navigate' ? { ignoreSearch: true } : {};
    return cache.match(key.href, options).then((cached) => {
      if (cached && !isRevalidatable(url.pathname)) return cached;

      const network = fetch(request).then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(key.href, copy));
        }
        return res;
      }).catch(() => cached);

      return cached || network;
    });
  });

  event.respondWith(promise);
});
