export const accessories = [
  {
    id: 'bloodfiendhair',
    name: 'Bloodfiend Hair',
    description: 'The hair of a true hero.',
    price: 30,
    author: 'Eliam',
     icon: 'B',
    meshPath: new URL('../assets/accessories/bloodfiendhair.glb', import.meta.url).href,
    category: 'Hair',
    created: 'June 9, 2026 4:10:00 PM',
    updated: 'September 9, 2026 5:09:19 PM',
  },
  {
    id: 'halo',
    name: 'Halo',
    description: 'A divine halo.',
    price: 20,
    author: 'BloxVerse',
     icon: 'H',
    meshPath: new URL('../assets/accessories/halo.glb', import.meta.url).href,
    category: 'Hat',
    created: 'September 9, 2026 6:02:19 PM',
    updated: 'September 9, 2026 6:02:19 PM',
  },
  {
    id: 'tophat',
    name: 'Top Hat',
    description: 'A classic top hat.',
    price: 30,
    author: 'BloxVerse',
     icon: 'T',
    meshPath: new URL('../assets/accessories/tophat.glb', import.meta.url).href,
    category: 'Hat',
    created: 'September 9, 2026 6:02:19 PM',
    updated: 'September 9, 2026 6:02:19 PM',
  },
  {
    id: 'stickynote',
    name: 'Sticky Note',
    description: 'My name is Bloxversian.',
    price: 20,
    author: 'BloxVerse',
     icon: 'T',
    meshPath: new URL('../assets/accessories/stickynote.glb', import.meta.url).href,
    category: 'Front Accessory',
    created: 'September 9, 2026 6:02:19 PM',
    updated: 'September 9, 2026 6:02:19 PM',
  },
  {
    id: 'minibloxversian',
    name: 'Mini Bloxversian',
    description: "It's me! but smaller!",
    price: 45,
    author: 'BloxVerse',
     icon: 'M',
    meshPath: new URL('../assets/accessories/minibloxversian.glb', import.meta.url).href,
    category: 'Hat',
    created: 'September 10, 2026 5:30:06 PM',
    updated: 'September 10, 2026 5:30:06 PM',
  },
  {
    id: 'burgerhead',
    name: 'Burger Head',
    description: 'Woah! My head is a burger!',
    price: 55,
    author: 'BloxVerse',
     icon: 'B',
    meshPath: new URL('../assets/accessories/burgerhead.glb', import.meta.url).href,
    category: 'Hat',
    created: 'September 10, 2026 8:46:06 PM',
    updated: 'September 10, 2026 8:46:06 PM',
  },
  {
    id: 'goldcrank',
    name: 'Gold Crank',
    description: 'Become a windup toy.',
    price: 20,
    author: 'BloxVerse',
     icon: 'G',
    meshPath: new URL('../assets/accessories/goldcrank.glb', import.meta.url).href,
    category: 'Back Accessory',
    created: 'September 11, 2026 5:49:24 PM',
    updated: 'September 11, 2026 5:49:24 PM',
  },
  {
    id: 'eyepoppers',
    name: 'Eye Poppers',
    description: 'My eyes!',
    price: 25,
    author: 'BloxVerse',
     icon: 'E',
    meshPath: new URL('../assets/accessories/eyepoppers.glb', import.meta.url).href,
    category: 'Face Accessory',
    created: 'September 11, 2026 6:16:22 PM',
    updated: 'September 11, 2026 6:16:22 PM',
  },
  {
    id: 'classicbowtie',
    name: 'Classic Bowtie',
    description: 'A timeless accessory for any occasion.',
    price: 30,
    author: 'BloxVerse',
     icon: 'C',
    meshPath: new URL('../assets/accessories/classicbowtie.glb', import.meta.url).href,
    category: 'Face Accessory',
    created: 'September 11, 2026 8:40:06 PM',
    updated: 'September 11, 2026 8:40:06 PM',
  },
]

export function getAllAccessories() {
  return accessories
}

export function findAccessory(id) {
  return accessories.find(a => a.id === id) || null
}
