export const clothingItems = [
  {
    id: 'i-love-bloxverse',
    name: 'I ❤️ BloxVerse',
    description: 'Show your love for BloxVerse with this classic t-shirt!',
    price: 0,
    author: 'BloxVerse',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/i❤️bloxverse.png', import.meta.url).href,
  },
  {
    id: 'shirt-template-blank',
    name: 'Blank Shirt Template',
    description: 'A completely blank template to use as a starting point for your own designs.',
    price: 0,
    author: 'BloxVerse',
    category: 'Templates',
    texturePath: new URL('../assets/clothing/shirtTemplateBlank.png', import.meta.url).href,
  },
  {
    id: 'template-shirts-r15',
    name: 'R15 Shirt Template',
    description: 'The standard R15 shirt template layout reference.',
    price: 0,
    author: 'BloxVerse',
    category: 'Templates',
    texturePath: new URL('../assets/clothing/Template-Shirts-R15.png', import.meta.url).href,
  },
  {
    id: 'egyptianshirt',
    name: 'Egyptian',
    description: 'Represent the ancient civilization with this Egyptian-themed shirt.',
    price: 10,
    author: 'BloxVerse',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/egyptianShirt.png', import.meta.url).href,
  },
  {
    id: 'colorful-joseph',
    name: 'Colorful',
    description: 'A vibrant and colorful shirt made by Joseph.',
    price: 0,
    author: 'Joseph',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/colorfulJoseph.png', import.meta.url).href,
  },
  {
    id: 'bloxverseenthusiast',
    name: 'BloxVerse Enthusiast',
    description: 'Show your passion for BloxVerse with this exclusive shirt.',
    price: 10,
    author: 'Zarif',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/bloxverseEnthusiast.png', import.meta.url).href,
  },
  {
    id: 'basicsuit',
    name: 'Basic Suit',
    description: 'A simple and classic suit for any occasion.',
    price: 20,
    author: 'BloxVerse',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/basicSuit.png', import.meta.url).href,
  },
  {
    id: 'blueandblackmotorcycleshirt',
    name: 'Blue and Black Motorcycle Shirt',
    description: 'Classic blue t-shirt with a black motorcycle design on the front.',
    price: 0,
    author: 'BloxVerse',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/blueAndBlackMotorcycleShirt.png', import.meta.url).href,
  },
  {
    id: 'duckshirt',
    name: 'Duck',
    description: 'A classic black t-shirt with a duck on the front.',
    price: 20,
    author: 'BloxVerse',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/duck.png', import.meta.url).href,
  },
  {
    id: 'ronaldoshirt',
    name: 'Ronaldo Shirt',
    description: 'A stylish red shirt with green stripes designed after the famous footballer Cristiano Ronaldo.',
    price: 15,
    author: 'BloxVerse',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/ronaldoShirt.png', import.meta.url).href,
  },
  {
    id: 'fadebearhoodie',
    name: 'Fade Bear Hoodie',
    description: 'A cozy gradient hoodie with a bear design.',
    price: 25,
    author: 'BloxVerse',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/fadeBearHoodie.png', import.meta.url).href,
  },
  {
    id: 'blockyfightshirt',
    name: 'Blocky Fight Shirt',
    description: 'A shirt to represent your fighting skills.',
    price: 15,
    author: 'BloxVerse',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/blockyFightShirt.png', import.meta.url).href,
  },
  {
    id: 'yellowcamoshirt',
    name: 'Yellow Camo Shirt',
    description: 'A yellow camo shirt to stay hidden by blending in with nearby environments.',
    price: 30,
    author: 'BloxVerse',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/yellowCamoShirt.png', import.meta.url).href,
  },
  {
    id: 'perkypolosweater',
    name: 'Polo Sweater',
    description: 'A cozy and comfy sweater with appealing colors.',
    price: 25,
    author: 'Perky',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/perkyPoloSweater.png', import.meta.url).href,
  },
  {
    id: 'tancamoshirt',
    name: 'Tan Camo Shirt',
    description: 'A tan camo shirt to stay hidden by blending in with nearby environments.',
    price: 30,
    author: 'BloxVerse',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/tanCamoShirt.png', import.meta.url).href,
  },
  {
    id: 'mikushirt',
    name: 'Miku Shirt',
    description: 'A cute shirt based on the popular character Miku.',
    price: 39,
    author: 'hi :D',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/ukiMShirt.png', import.meta.url).href,
  },
  {
    id: 'bloxverseshirt',
    name: 'BloxVerse Shirt',
    description: 'A shirt to show your appreciation for Bloxverse.',
    price: 12,
    author: 'Perky',
    category: 'Shirts',
    texturePath: new URL('../assets/clothing/bloxverseShirt.png', import.meta.url).href,
  },
];

export function getAllClothing() {
  return clothingItems.slice();
}

export function findClothing(id) {
  return clothingItems.find(item => item.id === id) || null;
}

export {
  applyAvatarClothing,
  removeAvatarClothing,
} from './avatar-clothing.js';
